def pattern_count(text, pattern):
    count = 0
    for i in range(0, len(text)-len(pattern)):
        if text[i:i+len(pattern)] == pattern:
            count += 1
    return count


def frequent_words(text, k):
    frequent_patterns = []
    count = {}
    maximum = 0
    for i in range(0, len(text) - k):
        count[i] = pattern_count(text, text[i:i+k])
        if count[i] > maximum:
            maximum = count[i]
    for i in range(0, len(text) - k):
        if count[i] == maximum and text[i:i+k] not in frequent_patterns:
            frequent_patterns.append(text[i:i+k])
    return frequent_patterns

pattern = 'ACT'
text = 'GAGGGCTTCTCAGGGGTTGAGGGCTTCCCAGCGTACCAGCGTATAGAGCCTCCAGCGTATAGAGCCTTAGAGCCTCCAGCGTACCAGCGTATCAGGGGTTTCAGGGGTTTCAGGGGTTAATCAACAATCAACTCAGGGGTTAATCAACAATCAACTCAGGGGTTTAGAGCCTTAGAGCCTCCAGCGTAGAGGGCTTCCCAGCGTAGAGGGCTTCTAGAGCCTAATCAACTCAGGGGTTGAGGGCTTCGAGGGCTTCTCAGGGGTTAATCAACTAGAGCCTTAGAGCCTAATCAACTAGAGCCTCCAGCGTAGAGGGCTTCGAGGGCTTCGAGGGCTTCAATCAACTAGAGCCTAATCAACTCAGGGGTTTCAGGGGTTCCAGCGTAAATCAACAATCAACTAGAGCCTTAGAGCCTTAGAGCCTAATCAACTAGAGCCTTAGAGCCTTAGAGCCTTAGAGCCTGAGGGCTTCGAGGGCTTCAATCAACAATCAACTAGAGCCTTCAGGGGTTAATCAACTAGAGCCTGAGGGCTTCGAGGGCTTCCCAGCGTATCAGGGGTTGAGGGCTTCAATCAACGAGGGCTTCTAGAGCCTAATCAACAATCAACAATCAACCCAGCGTAGAGGGCTTCTCAGGGGTTAATCAACTAGAGCCTAATCAACTCAGGGGTTGAGGGCTTCTCAGGGGTTAATCAACAATCAACTAGAGCCTGAGGGCTTCCCAGCGTACCAGCGTACCAGCGTAAATCAACGAGGGCTTCCCAGCGTATAGAGCCTTCAGGGGTTGAGGGCTTCCCAGCGTAAATCAACTCAGGGGTTTAGAGCCTGAGGGCTTCTAGAGCCTGAGGGCTTCCCAGCGTAAATCAAC'
print pattern_count(text, pattern)
print frequent_words(text, 11)